
exports.PAYMENT_STATUS_NEW = 0;
exports.PAYMENT_STATUS_PROCESSED = 1;
exports.PAYMENT_STATUS_ERROR = 2;
exports.PAYMENT_STATUS_REJECTED = 3;
exports.PAYMENT_STATUS_DELETED = 4;




exports.PAYEMNT_TYPE_PAYPAL = 0;




exports.PAYPAL_ERROR_BAD_PREAPPROOVAL='569017';
exports.PAYPAL_ERROR_BAD_PINCODE='580022';